# Generated by Django 2.1.4 on 2018-12-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20181215_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='meal_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('cost', models.IntegerField()),
                ('totalcost', models.IntegerField()),
                ('description', models.CharField(max_length=80)),
            ],
        ),
    ]
