# Generated by Django 2.1.4 on 2018-12-16 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_meal_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_info',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.employee_info'),
        ),
    ]
