# Generated by Django 2.1.4 on 2018-12-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20181216_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_info',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
