# Generated by Django 2.1.4 on 2018-12-16 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20181216_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal_info',
            name='dtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 11, 50, 18, 51583)),
        ),
    ]
